### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by justscribe** [alexeevdv/yii2-recaptcha-widget#2]
Hi.
Messages dont loading (directory "messages/en") through composer into vendor directory.
And we have error "Unable to locate message source for category 'recaptcha'."
Thanks.

**Comment by justscribe** [comment]
All ok=)

**Comment by alexeevdv** [comment]
Hi. I'll take a look today. Should be a simple fix

**Comment by alexeevdv** [comment]
It is fixed in `dev-master`, i'll release fixed version tomorrow when i add some more tests

**Comment by alexeevdv** [comment]
Fixed in 1.1.1
