### ISSUE TITLE
Just a simple question

### ISSUE THREAD

**Issue by moplin** [alexeevdv/yii2-recaptcha-widget#3]
May be I am missing something.
I already did configuration, and the reCatcha is showing, but is not validating on the form, its just sending the form and then failing.
In the model rules:
`['recaptcha', RecaptchaValidator::className()]`

In the form.
`
                echo  RecaptchaWidget::widget([
                    "siteKey" => $settings->get('google', 'data-sitekey'),
                    "model" => $model,
                    "attribute" => 'recaptcha',
                ]);
`
Please some help.

**Comment by alexeevdv** [comment]
If you configured `recaptcha` component then you don't need `siteKey` param in widget.

Just try this: 
```php
echo RecaptchaWidget::widget(['model' => $model, 'attribute' => 'recaptcha']);
```

If you NOT configured `recaptcha` component then you need to specify siteSecret in validator config. Like this:
```php
['recaptcha', RecaptchaValidator::class, 'secret' => 'YOUR_SECRET'], 
```

Also try to update extension to the latest version (1.1.1)

**Comment by moplin** [comment]
I ended using your reCaptha without $model, it rocks.
I couldn't make it work whith model validation.
So, if you like I can help a bit by updating documentation on how to do this, and also messages in spanish if you like.
-Pablo

**Comment by alexeevdv** [comment]
Messages in spanish would be great. As for model validation issue... it could be something wrong with your own code. I use this extension in my own projects and never faced such problem

**Comment by moplin** [comment]
Yep probably something dumb I am missing, but the model-less validation saved me, you know not much time.
Thanks
