### ISSUE TITLE
Yii::debug since 2.0.14

### ISSUE THREAD

**Issue by raoptimus** [alexeevdv/yii2-recaptcha-widget#7]
The widget is not working in yii < 2.0.14, that validator has Yii::debug method
It will need fixes in composer requirements

**Comment by alexeevdv** [comment]
Yes, you are right. I'll fix backward compatibility soon. Thanks for posting the issue

**Comment by alexeevdv** [comment]
Fixed in 1.1.2

**Comment by raoptimus** [comment]
Thank you
